# Generated by Django 5.2.6 on 2025-09-05 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('room_no', models.CharField(max_length=10)),
                ('base_rent', models.IntegerField(default=1000)),
                ('food_fee', models.IntegerField(default=3000)),
            ],
        ),
        migrations.CreateModel(
            name='MessCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentIceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('icecream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.icecream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_app.student')),
            ],
        ),
    ]
