# Generated by Django 5.2.6 on 2025-09-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='base_rent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='food_fee',
        ),
        migrations.AddField(
            model_name='student',
            name='extra_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
    ]
